/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CreateShopRouteImport } from './routes/create-shop'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShopLoginRouteImport } from './routes/shop-login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminShopsRouteImport } from './routes/admin/shops'
import { Route as OrderReceiptIdRouteImport } from './routes/order.$receiptId'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts.index'
import { Route as ReceiptsReceiptIdRouteImport } from './routes/receipts.$receiptId'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopShopIdRouteImport } from './routes/shop.$shopId'
import { Route as ShopAnalyticsRouteImport } from './routes/shop.analytics'
import { Route as ShopChangePasswordRouteImport } from './routes/shop.change-password'
import { Route as ShopCustomersRouteImport } from './routes/shop.customers'
import { Route as ShopMenuRouteImport } from './routes/shop.menu'
import { Route as ShopOrdersRouteImport } from './routes/shop.orders'
import { Route as ShopPaymentsRouteImport } from './routes/shop.payments'
import { Route as ShopSettingsRouteImport } from './routes/shop.settings'
import { Route as AdminShopsCreateRouteImport } from './routes/admin/shops.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateShopRoute = CreateShopRouteImport.update({
  id: '/create-shop',
  path: '/create-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopLoginRoute = ShopLoginRouteImport.update({
  id: '/shop-login',
  path: '/shop-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const OrderReceiptIdRoute = OrderReceiptIdRouteImport.update({
  id: '/order/$receiptId',
  path: '/order/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsReceiptIdRoute = ReceiptsReceiptIdRouteImport.update({
  id: '/receipts/$receiptId',
  path: '/receipts/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopShopIdRoute = ShopShopIdRouteImport.update({
  id: '/shop/$shopId',
  path: '/shop/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAnalyticsRoute = ShopAnalyticsRouteImport.update({
  id: '/shop/analytics',
  path: '/shop/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopChangePasswordRoute = ShopChangePasswordRouteImport.update({
  id: '/shop/change-password',
  path: '/shop/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCustomersRoute = ShopCustomersRouteImport.update({
  id: '/shop/customers',
  path: '/shop/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopMenuRoute = ShopMenuRouteImport.update({
  id: '/shop/menu',
  path: '/shop/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/shop/orders',
  path: '/shop/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopPaymentsRoute = ShopPaymentsRouteImport.update({
  id: '/shop/payments',
  path: '/shop/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSettingsRoute = ShopSettingsRouteImport.update({
  id: '/shop/settings',
  path: '/shop/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopsCreateRoute = AdminShopsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminShopsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/create-shop': typeof CreateShopRoute
  '/favourites': typeof FavouritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/shop-login': typeof ShopLoginRoute
  '/signup': typeof SignupRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/order/$receiptId': typeof OrderReceiptIdRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/shop/analytics': typeof ShopAnalyticsRoute
  '/shop/change-password': typeof ShopChangePasswordRoute
  '/shop/customers': typeof ShopCustomersRoute
  '/shop/menu': typeof ShopMenuRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/payments': typeof ShopPaymentsRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/shops/create': typeof AdminShopsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/create-shop': typeof CreateShopRoute
  '/favourites': typeof FavouritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/shop-login': typeof ShopLoginRoute
  '/signup': typeof SignupRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/order/$receiptId': typeof OrderReceiptIdRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/shop/analytics': typeof ShopAnalyticsRoute
  '/shop/change-password': typeof ShopChangePasswordRoute
  '/shop/customers': typeof ShopCustomersRoute
  '/shop/menu': typeof ShopMenuRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/payments': typeof ShopPaymentsRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/receipts': typeof ReceiptsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/admin/shops/create': typeof AdminShopsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/create-shop': typeof CreateShopRoute
  '/favourites': typeof FavouritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/shop-login': typeof ShopLoginRoute
  '/signup': typeof SignupRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/order/$receiptId': typeof OrderReceiptIdRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/shop/analytics': typeof ShopAnalyticsRoute
  '/shop/change-password': typeof ShopChangePasswordRoute
  '/shop/customers': typeof ShopCustomersRoute
  '/shop/menu': typeof ShopMenuRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/payments': typeof ShopPaymentsRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/shops/create': typeof AdminShopsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/create-shop'
    | '/favourites'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/shop-login'
    | '/signup'
    | '/admin/shops'
    | '/order/$receiptId'
    | '/receipts/$receiptId'
    | '/shop/$shopId'
    | '/shop/analytics'
    | '/shop/change-password'
    | '/shop/customers'
    | '/shop/menu'
    | '/shop/orders'
    | '/shop/payments'
    | '/shop/settings'
    | '/receipts/'
    | '/shop/'
    | '/admin/shops/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/create-shop'
    | '/favourites'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/shop-login'
    | '/signup'
    | '/admin/shops'
    | '/order/$receiptId'
    | '/receipts/$receiptId'
    | '/shop/$shopId'
    | '/shop/analytics'
    | '/shop/change-password'
    | '/shop/customers'
    | '/shop/menu'
    | '/shop/orders'
    | '/shop/payments'
    | '/shop/settings'
    | '/receipts'
    | '/shop'
    | '/admin/shops/create'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/create-shop'
    | '/favourites'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/shop-login'
    | '/signup'
    | '/admin/shops'
    | '/order/$receiptId'
    | '/receipts/$receiptId'
    | '/shop/$shopId'
    | '/shop/analytics'
    | '/shop/change-password'
    | '/shop/customers'
    | '/shop/menu'
    | '/shop/orders'
    | '/shop/payments'
    | '/shop/settings'
    | '/receipts/'
    | '/shop/'
    | '/admin/shops/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CreateShopRoute: typeof CreateShopRoute
  FavouritesRoute: typeof FavouritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ShopLoginRoute: typeof ShopLoginRoute
  SignupRoute: typeof SignupRoute
  OrderReceiptIdRoute: typeof OrderReceiptIdRoute
  ReceiptsReceiptIdRoute: typeof ReceiptsReceiptIdRoute
  ShopShopIdRoute: typeof ShopShopIdRoute
  ShopAnalyticsRoute: typeof ShopAnalyticsRoute
  ShopChangePasswordRoute: typeof ShopChangePasswordRoute
  ShopCustomersRoute: typeof ShopCustomersRoute
  ShopMenuRoute: typeof ShopMenuRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopPaymentsRoute: typeof ShopPaymentsRoute
  ShopSettingsRoute: typeof ShopSettingsRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-shop': {
      id: '/create-shop'
      path: '/create-shop'
      fullPath: '/create-shop'
      preLoaderRoute: typeof CreateShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-login': {
      id: '/shop-login'
      path: '/shop-login'
      fullPath: '/shop-login'
      preLoaderRoute: typeof ShopLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/order/$receiptId': {
      id: '/order/$receiptId'
      path: '/order/$receiptId'
      fullPath: '/order/$receiptId'
      preLoaderRoute: typeof OrderReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$receiptId': {
      id: '/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/receipts/$receiptId'
      preLoaderRoute: typeof ReceiptsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$shopId': {
      id: '/shop/$shopId'
      path: '/shop/$shopId'
      fullPath: '/shop/$shopId'
      preLoaderRoute: typeof ShopShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/analytics': {
      id: '/shop/analytics'
      path: '/shop/analytics'
      fullPath: '/shop/analytics'
      preLoaderRoute: typeof ShopAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/change-password': {
      id: '/shop/change-password'
      path: '/shop/change-password'
      fullPath: '/shop/change-password'
      preLoaderRoute: typeof ShopChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/customers': {
      id: '/shop/customers'
      path: '/shop/customers'
      fullPath: '/shop/customers'
      preLoaderRoute: typeof ShopCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/menu': {
      id: '/shop/menu'
      path: '/shop/menu'
      fullPath: '/shop/menu'
      preLoaderRoute: typeof ShopMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/orders': {
      id: '/shop/orders'
      path: '/shop/orders'
      fullPath: '/shop/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/payments': {
      id: '/shop/payments'
      path: '/shop/payments'
      fullPath: '/shop/payments'
      preLoaderRoute: typeof ShopPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/settings': {
      id: '/shop/settings'
      path: '/shop/settings'
      fullPath: '/shop/settings'
      preLoaderRoute: typeof ShopSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shops/create': {
      id: '/admin/shops/create'
      path: '/create'
      fullPath: '/admin/shops/create'
      preLoaderRoute: typeof AdminShopsCreateRouteImport
      parentRoute: typeof AdminShopsRoute
    }
  }
}

interface AdminShopsRouteChildren {
  AdminShopsCreateRoute: typeof AdminShopsCreateRoute
}

const AdminShopsRouteChildren: AdminShopsRouteChildren = {
  AdminShopsCreateRoute: AdminShopsCreateRoute,
}

const AdminShopsRouteWithChildren = AdminShopsRoute._addFileChildren(
  AdminShopsRouteChildren,
)

interface AdminRouteChildren {
  AdminShopsRoute: typeof AdminShopsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminShopsRoute: AdminShopsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CreateShopRoute: CreateShopRoute,
  FavouritesRoute: FavouritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ShopLoginRoute: ShopLoginRoute,
  SignupRoute: SignupRoute,
  OrderReceiptIdRoute: OrderReceiptIdRoute,
  ReceiptsReceiptIdRoute: ReceiptsReceiptIdRoute,
  ShopShopIdRoute: ShopShopIdRoute,
  ShopAnalyticsRoute: ShopAnalyticsRoute,
  ShopChangePasswordRoute: ShopChangePasswordRoute,
  ShopCustomersRoute: ShopCustomersRoute,
  ShopMenuRoute: ShopMenuRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopPaymentsRoute: ShopPaymentsRoute,
  ShopSettingsRoute: ShopSettingsRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
